base: "../testing"
sim_control_params:
  n_samples: 1000
  n_steps_per_sample: 1000
  nnp: "tautani2x"

analysis:
  lambda_scheme: [0, 0.1, 0.2, 0.4, 0.6, 0.8, 0.9, 1.0]
  lambda_val: null
  torsion_indices: [3, 2, 1, 5]

tautomer_systems:
  name: "tp_44" #acetaldehyde
  smiles_t1: "CC=O" #keto
  smiles_t2: "C=CO" #enol
  dG: 8.499589 